language: node_js
node_js:
  - node
  - 14
  - 12
  - 10
  - 8
sudo: false
node_js:
  - "stable"
script:
  - yarn install
  - yarn bootstrap
  - yarn build
  - yarn test:cov
  - yarn run typedoc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
before_deploy:
  - touch .nojekyll
  - sed -i 's/api-docs/api-docs-unignored/g' .gitignore
after_success:
  - node node_modules/.bin/coveralls <coverage/lcov.info
