anguage: node_js
sudo: false
node_js:
  - "stable"
script:
  - yarn install
  - yarn bootstrap
  - yarn test
after_success:
  - yarn run test:cov && node node_modules/.bin/coveralls <coverage/lcov.info
