language: node_js
sudo: false
node_js:
  - "stable"
script:
  - yarn install
  - yarn bootstrap
  - yarn build
  - yarn test:cov
after_success:
  - node node_modules/.bin/coveralls <coverage/lcov.info
