anguage: node_js
sudo: false
node_js:
  - "stable"
script:
  - yarn install
  - yarn bootstrap
  - yarn test
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN
#  on:
#    branch: master    
#before_deploy:
#  - touch .nojekyll
#  - sed -i '/api-docs/d' .gitignore
